#!/bin/python3

"""
This code defines a script which installs the third-party software necessary
for using this package.
"""

# Non-standard imports.
from hosker_utils import install_apt_packages

# Local constants.
APT_PACKAGES_TO_INSTALL = ("cargo", "libgmp-dev")

##############
# RUN SCRIPT #
##############

def run():
    """ Run this file. """
    return install_apt_package("cargo")

if __name__ == "__main__":
    run()
