#!/bin/python3

"""
This code defines a script which installs Cargo, which includes Rust.
"""

# Non-standard imports.
from hosker_utils import install_apt_package

##############
# RUN SCRIPT #
##############

def run():
    """ Run this file. """
    return install_apt_package("cargo")

if __name__ == "__main__":
    run()
